#!/usr/bin/env ruby

STDERR.puts "Starting Runner"

require './lib/omaha_bot'

begin
  OmahaBot.runner
rescue Exception => e
  STDERR.puts "Runner blew up! #{e.message}"
  e.backtrace.each do |trace|
    STDERR.puts trace
  end
  raise e
end
